### ISSUE TITLE
Failing test TestMapFileRecordReaderMultipleParts

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/DataVec#303]
#### Issue Description

At 9c16d8e1 Add multi-part support for MapFileSequenceRecordReader

```
Failed tests: 
  TestMapFileRecordReaderMultipleParts.testSequenceRecordReader:197 expected:<[(0, 2), (3, 5), (6, 8)]> but was:<[(6, 8), (3, 5), (0, 2)]>
```
log: https://gist.github.com/2a42a79219c3d98c78798a88d3cb1d0b

At 45f2a72c Add multi-part support to MapFileRecordReader + test

```
Failed tests: 
  TestMapFileRecordReaderMultipleParts.testRecordReaderMultipleParts:266 expected:<[(0, 2), (3, 5), (6, 8)]> but was:<[(6, 8), (3, 5), (0, 2)]>
  TestMapFileRecordReaderMultipleParts.testSequenceRecordReader:201 expected:<[(0, 2), (3, 5), (6, 8)]> but was:<[(6, 8), (3, 5), (0, 2)]>
```
log: https://gist.github.com/3e7b7364b987c9c739c843f5cbcef842

The failure persists on every commit until current master ( 675447ff )

**Comment by AlexDBlack** [comment]
Looks like this is a file iteration order issue when listing directories in Windows vs. Linux. This, (and also #305 but that might be a different cause) both pass consistently on Windows, and have done so since they were added.

I'll reproduce it on Linux first, however my fix will likely be different to that proposed in https://github.com/deeplearning4j/DataVec/pull/304 (i.e., at the reader level not the test level).

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/DataVec/pull/307
Thanks for flagging this.

**Comment by saudet** [comment]
I think I remember seeing something like this before. Windows's file system keeps files listed in alphabetical order, but that's not usually the case on Linux...

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Image support for the Transform process](https://trello.com/c/tyLqHQPH/4-image-support-for-the-transform-process)
