### ISSUE TITLE
(Presumably) incorrect input to FFT in Spectrogram/FastFourierTransform

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/DataVec#502]
#### Issue Description

Spectrogram through FastFourierTransform gives com.sun.media.sound.FFT.transform a double array of real valued signal amplitudes while it expects a complex double array with same format as the output (even indexes are real and odd are imaginary). 

The result is that the output can to the extent of my knowledge not really be called the fft of the signal. It also has the more visible consequence that the fft produced is only a quarter of the signal length instead of half (half is expected since negative freqs are discarded).

I don't know if this is some kind of Deep Learning trick, but at least for me the accuracy of my classifier improved slightly when I changed the implementation.

Something like this does the trick (sorry about lack of formatting):

 final int sampleSize = 2*signals[0].length;
 FFT fft = new FFT(sampleSize/2, -1);

double[] signalsAsComplex = new double[sampleSize];
for(int j = 0; j < sampleSize; j+=2) {
      signalsAsComplex[j] = signals[i][j/2];
      signalsAsComplex[j+1] = 0; // Can be omitted if one trusts in initialization
}
fft.transform(signalsAsComplex); 

Obviously if one wants to retain the possibility to fft complex signals the code above needs to go into Spectrogram.java instead.

#### Version Information

Present in latest version of Spectrogram (a8744ac on Jul 10 2017) /FastFourierTransform (2850231 Feb 28, 2017)

#### Contributing

Trivial fix. Unsure about desired approach wrt complex signals and model backwards compatibility (e.g. third parties models build on this version of the file).

**Comment by saudet** [comment]
I think the current implementation is just not correct, so please make the necessary modifications and send a pull request! BTW, we should probably switch to FFTW for performance reasons and because  com.sun.media.sound.FFT is not available on Android or with Java 9 anymore:
https://github.com/bytedeco/javacpp-presets/tree/master/fftw
However, since that is under the GPL license, we'd have to disable it by default as with FFmpeg:
https://github.com/deeplearning4j/DataVec/blob/master/datavec-data/datavec-data-codec/pom.xml#L53
