### ISSUE TITLE
Binary format serialization for records

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#77]
New interface: 

Add  concept of a record. A record knows how to read and write itself (similar to writables).

Goal: Make datavec more susceptible to binary data formatting.

Records should also be convertable to List<Writable> for interop purposes. 

Problem: right now there is a lot of GC rpessure when building data pipelines. We want to reduce this.

A few considerations for the binary format:
Queryable for size: There will likely be different kinds of records.
One of those would be something simple like a csv "record" which could have any number of columns
and various kinds of data in it. 

Time series: Make time series more compact by allowing things like time step indexing. This would be similar to hadoop's sequence files.

Ideally we represent this with something like arrow? 
http://arrow.apache.org/

**Comment by AlexDBlack** [comment]
One option I was thinking here: use (or modify) the Record/SequenceRecord interfaces, with abstracted away storage
https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/records/Record.java
https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/records/SequenceRecord.java

so a SequenceRecord implementation could be backed by either a List<List<Writable>> when we have text or are doing transforms on dirty data, or an INDArray in general, or maybe something else down the line. Instances would have conversion methods, such as toINDArray() and hasINDArray().
This might be a quick way to move towards binarization, without doing too much of a rewrite. Then switch the APIs (for Transforms etc) from ```List<Writable>``` to Record; we can still call ```List<Writable> getRecord();``` when we need a ```List<Writable>```, or just call ```toINDArray()``` otherwise.

In the RecordReaders/SequenceRecordReaders, they could then decide to binarize on loading (say, CSV that matches a regex for "is entirely numerical"), or fall back to ```List<Writable>``` otherwise.

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by agibsonccc** [comment]
Kind of - arrow was a huge step in the right direction for this. It's only really a "half way" point though.

**Comment by AlexDBlack** [comment]
I think we close this as resolved - we have the arrow/INDArray ```List<Writable>``` wrappers, binary format for saving (map file, arrow) etc.
For the internal representation that's basically the proposed rewrite.
